apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-krug-clb2
  name: aws-kurg-clb2
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer